//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EatOnTimeApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERROR_LOG
    {
        public int ERROR_LOG_ID { get; set; }
        public string ERROR_LOG_CODE { get; set; }
        public string ERROR_LOG_DESC { get; set; }
        public string OBJECT_NAME { get; set; }
        public string PROCEDURE_NAME_ { get; set; }
        public string LINE { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
    }
}
