//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EatOnTimeApi
{
    using System;
    
    public partial class GET_TABLE_ORDER_Result1
    {
        public Nullable<int> QTY_PO { get; set; }
        public Nullable<double> UNIT_PRICE { get; set; }
        public string PRODUCT_NAME { get; set; }
        public int ORDER_ID { get; set; }
        public string PRODUCT_CODE { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public string SERVED { get; set; }
    }
}
