//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EatOnTimeApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU
    {
        public MENU()
        {
            this.PRODUCT_IN_MENU = new HashSet<PRODUCT_IN_MENU>();
            this.SESSION_PREFERENCES = new HashSet<SESSION_PREFERENCES>();
        }
    
        public int MENU_ID { get; set; }
        public string MENU_DESC { get; set; }
        public string MENU_TITLE { get; set; }
        public string XML_MENU_DETAIL { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
    
        public virtual ICollection<PRODUCT_IN_MENU> PRODUCT_IN_MENU { get; set; }
        public virtual ICollection<SESSION_PREFERENCES> SESSION_PREFERENCES { get; set; }
    }
}
