//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EatOnTimeApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_ORDER
    {
        public int PRODUCT_ORDER_ID { get; set; }
        public string PRODUCT_CODE { get; set; }
        public int ORDER_ID { get; set; }
        public string SERVED { get; set; }
        public Nullable<System.DateTime> SERVED_AT { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<int> QTY_PO { get; set; }
    
        public virtual PRODUCT_DETAIL PRODUCT_DETAIL { get; set; }
        public virtual RORDER RORDER { get; set; }
    }
}
