//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EatOnTimeApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_DETAIL
    {
        public PRODUCT_DETAIL()
        {
            this.PRODUCT_IN_MENU = new HashSet<PRODUCT_IN_MENU>();
            this.PRODUCT_ORDER = new HashSet<PRODUCT_ORDER>();
        }
    
        public string PRODUCT_CODE { get; set; }
        public string PRODUCT_DESC { get; set; }
        public Nullable<double> UNIT_PRICE { get; set; }
        public string PRODUCT_TYPE { get; set; }
        public int STATUS_ID { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public string PRODUCT_NAME { get; set; }
    
        public virtual ICollection<PRODUCT_IN_MENU> PRODUCT_IN_MENU { get; set; }
        public virtual STATUS_DETAIL STATUS_DETAIL { get; set; }
        public virtual ICollection<PRODUCT_ORDER> PRODUCT_ORDER { get; set; }
    }
}
