//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EatOnTimeApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_IN_MENU
    {
        public string PRODUCT_CODE { get; set; }
        public int MENU_ID { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<System.DateTime> CREATED_BY { get; set; }
    
        public virtual MENU MENU { get; set; }
        public virtual PRODUCT_DETAIL PRODUCT_DETAIL { get; set; }
    }
}
