//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EatOnTimeApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class RORDER
    {
        public RORDER()
        {
            this.PRODUCT_ORDER = new HashSet<PRODUCT_ORDER>();
        }
    
        public int ORDER_ID { get; set; }
        public int TABLE_ACTIVITY_ID { get; set; }
        public int STATUS_ID { get; set; }
        public Nullable<double> ORDER_TOTAL { get; set; }
        public Nullable<double> ORDER_SUBTOTAL { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
    
        public virtual ICollection<PRODUCT_ORDER> PRODUCT_ORDER { get; set; }
        public virtual STATUS_DETAIL STATUS_DETAIL { get; set; }
        public virtual TABLE_ACTIVITY TABLE_ACTIVITY { get; set; }
    }
}
