//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EatOnTimeApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTABLES
    {
        public RTABLES()
        {
            this.TABLE_ACTIVITY = new HashSet<TABLE_ACTIVITY>();
        }
    
        public int TABLE_ID { get; set; }
        public string TABLE_CODE { get; set; }
        public string LOCATION_DESC { get; set; }
        public Nullable<int> QTY_LIMIT { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<int> STATUS_ID { get; set; }
    
        public virtual STATUS_DETAIL STATUS_DETAIL { get; set; }
        public virtual ICollection<TABLE_ACTIVITY> TABLE_ACTIVITY { get; set; }
    }
}
