//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EatOnTimeApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATUS_DETAIL
    {
        public STATUS_DETAIL()
        {
            this.PRODUCT_DETAIL = new HashSet<PRODUCT_DETAIL>();
            this.RORDER = new HashSet<RORDER>();
            this.RTABLES = new HashSet<RTABLES>();
            this.TABLE_ACTIVITY = new HashSet<TABLE_ACTIVITY>();
        }
    
        public int STATUS_ID { get; set; }
        public string STATUS_DESC { get; set; }
    
        public virtual ICollection<PRODUCT_DETAIL> PRODUCT_DETAIL { get; set; }
        public virtual ICollection<RORDER> RORDER { get; set; }
        public virtual ICollection<RTABLES> RTABLES { get; set; }
        public virtual ICollection<TABLE_ACTIVITY> TABLE_ACTIVITY { get; set; }
    }
}
