//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EatOnTimeApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLE_ACTIVITY
    {
        public TABLE_ACTIVITY()
        {
            this.RORDER = new HashSet<RORDER>();
        }
    
        public int TABLE_ACTIVITY_ID { get; set; }
        public int TABLE_ID { get; set; }
        public Nullable<int> STATUS_ID { get; set; }
        public Nullable<double> ORDER_TOTAL { get; set; }
        public Nullable<double> ORDER_SUB_TOTAL { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<int> QTY { get; set; }
    
        public virtual ICollection<RORDER> RORDER { get; set; }
        public virtual RTABLES RTABLES { get; set; }
        public virtual STATUS_DETAIL STATUS_DETAIL { get; set; }
    }
}
