//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EatOnTimeApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        public USERS()
        {
            this.SESSION_PREFERENCES = new HashSet<SESSION_PREFERENCES>();
        }
    
        public int R_USER_ID { get; set; }
        public string R_USER_NAME { get; set; }
        public byte[] USER_PASSWORD { get; set; }
        public string USER_ROLE { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
    
        public virtual ICollection<SESSION_PREFERENCES> SESSION_PREFERENCES { get; set; }
    }
}
